### ISSUE TITLE
1.15.2 Crash on loading

### ISSUE THREAD

**Issue by Yamza** [nevoka-be/BetterBedrockGenerator#4]
**Describe the bug**
betterbedrockgenerator-1.15.2-0.0.5 Crashes at game initialization. 0.0.4 works as expected.
Mixin bootstrap is included.

**Logs/crashlogs/etc**
https://hatebin.com/ofhugdqdqf

**Minecraft enviroment (please complete the following information):**
 - OS: Windows
 - Ram allocated 4GB
 - Minecraft & Forge version [1.15.2 - 31.0.1]
 - Mod Version [e.g. 0.0.5]

**Comment by JayJay1989** [comment]
can you post the full log please

**Comment by JayJay1989** [comment]
Recreated and found the actual problem. Will be fixed in next version.

**Comment by Yamza** [comment]
Seems like I'm still getting this on 0.0.6. This is all I get of a log as well. https://hatebin.com/qvtjlgzgcf

**Comment by JayJay1989** [comment]
@Yamza did you remove that log?
