### ISSUE TITLE
Crash with Ratlantis Dim from Rat mod

### ISSUE THREAD

**Issue by Sunekaer** [nevoka-be/BetterBedrockGenerator#5]
**Describe the bug**
Crash with Ratlantis Dim from Rat mod

**To Reproduce**
https://github.com/FTBTeam/FTB-Omnia/issues/87

**Logs/crashlogs/etc**
https://paste.sunekaer.com/azuwinatov.rb

**Expected behavior**

**Minecraft enviroment (please complete the following information):**
 - OS: Linux
 - Minecraft & Forge version 1.15.2-31.1.87
 - Mod Version 1.15.2-0.0.6

**Comment by JayJay1989** [comment]
@Sunekaer , i just created a test server with only citadel(1.1.7), rats(5.3.1) and BBG (0.0.6).
Everything works just fine. Do you remap any dimension with a mod?

**Comment by Sunekaer** [comment]
Hi
No we dont remap anything

**Comment by JayJay1989** [comment]
Can you reproduce this bug with updated Rats and Citadel mods? It could be a Rats problem

**Comment by JayJay1989** [comment]
@Sunekaer cannot be reproduced in the newer version of Rats.

**Comment by Sunekaer** [comment]
Hmm no ill let you know if it happens again, thanks for your assistant
