### ISSUE TITLE
[1.15.2] Crash whilst generating land on a server.

### ISSUE THREAD

**Issue by Gbergz** [nevoka-be/BetterBedrockGenerator#6]
**Describe the bug**
Server crashes sometimes while people are online generating.

**To Reproduce**
1. Log into a Server
2. Run around
3. Generate more of the world.
4. Crash.

**Logs/crashlogs/etc**
[Gist Paste](https://gist.github.com/Gbergz/ef3e9244bb463d8a1e4f68dcf0be55e6)

**Expected behavior**
Server not crashing whilst running around generating.

**Minecraft enviroment (please complete the following information):**
 - OS: Windows on client, but Ubuntu/Linux on server.
 - Ram allocated: 8 GB
 - Minecraft & Forge version: 31.1.74
 - Mod Version: 0.0.6

Any ideas?
- Gbergz

**Comment by JayJay1989** [comment]
#5 old rats version

**Comment by JayJay1989** [comment]
but will hardcode a check for null
