### ISSUE TITLE
[1.16.1] Spam in console when generating chunks.

### ISSUE THREAD

**Issue by Gbergz** [nevoka-be/BetterBedrockGenerator#7]
**Describe the bug**
Console is being spammed by the message:
``[be.ne.be.BetterBedrockGenerator/]: Dimension: minecraft:overworld``
When any chunks are being generated.

**To Reproduce**
1. Install the Mod
2. Start a Server w/ the mod
3. Join the Server
4. Look into console to see spam.

**Logs/crashlogs/etc**
https://gist.github.com/Gbergz/7f1d27952d749bf1c6169c0c25e64b73

**Expected behavior**
No spamming into console like last version of the mod.

**Screenshots**
![image](https://user-images.githubusercontent.com/26634554/87535603-0df96c00-c698-11ea-9723-8be95dab662d.png)

**Minecraft enviroment (please complete the following information):**
 - OS:Windows 10
 - Ram allocated: 7gb
 - Minecraft & Forge version 1.16.1 - 32.0.66
 - Mod Version: 0.0.8

**Comment by JayJay1989** [comment]
oops, my bad. Was debugging the nether roof bedrock not generating. Will be fixed in next version
